import { Role } from '@/types/auth';

export interface MenuDefinition {
  title: string;
  path: string;
  icon?: string;
  submenus?: MenuDefinition[];
}

export const MENUS_BY_ROLE: Record<Role, MenuDefinition[]> = {
  Developer: [
    { title: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { title: 'Backup do Sistema', path: '/dashboard/backup', icon: 'DatabaseBackup' },
    { title: 'Limpar ERP / Novo Início', path: '/dashboard/reset', icon: 'RotateCcw' },
    { title: 'Servidor & API Backend', path: '/dashboard/server', icon: 'Server' },
    { title: 'Análises de APIs e Segurança', path: '/dashboard/analytics', icon: 'ShieldAlert' },
    // Acesso a todos os do CEO abaixo...
    { title: 'Clientes', path: '/dashboard/clientes', icon: 'Users' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao', icon: 'Kanban' },
    { title: 'Ordem de serviço', path: '/dashboard/os', icon: 'ClipboardList' },
    { title: 'Estoque', path: '/dashboard/estoque', icon: 'Package' },
    { title: 'Funcionários', path: '/dashboard/funcionarios', icon: 'UserCircle' },
    { title: 'Relatórios', path: '/dashboard/relatorios', icon: 'FileText' },
    { title: 'Histórico de OS', path: '/dashboard/historico-os', icon: 'History' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens', icon: 'MessageSquare' },
    { title: 'Caixa PDV', path: '/dashboard/pdv', icon: 'Store' },
    { title: 'Configurações', path: '/dashboard/configuracoes', icon: 'Settings' },
  ],
  CEO: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Ordem de serviço com caixa pdv', path: '/dashboard/os' },
    { title: 'Estoque', path: '/dashboard/estoque' },
    { title: 'Funcionários', path: '/dashboard/funcionarios' },
    { title: 'Relatórios', path: '/dashboard/relatorios' },
    { title: 'Histórico de OS', path: '/dashboard/historico-os' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Caixa PDV (vendas diretas)', path: '/dashboard/pdv' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  'Gerente Geral': [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Ordem de serviço com caixa pdv', path: '/dashboard/os' },
    { title: 'Estoque', path: '/dashboard/estoque' },
    { title: 'Funcionários', path: '/dashboard/funcionarios' },
    { title: 'Relatórios', path: '/dashboard/relatorios' },
    { title: 'Histórico de OS', path: '/dashboard/historico-os' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Caixa PDV (vendas diretas)', path: '/dashboard/pdv' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Supervisor: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Ordem de serviço com caixa pdv', path: '/dashboard/os' },
    { title: 'Estoque', path: '/dashboard/estoque' },
    { title: 'Funcionários', path: '/dashboard/funcionarios' },
    { title: 'Relatórios', path: '/dashboard/relatorios' },
    { title: 'Histórico de OS', path: '/dashboard/historico-os' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Caixa PDV (vendas diretas)', path: '/dashboard/pdv' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Monitor: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  'Vendedor(a)': [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Ordem de serviço com caixa pdv', path: '/dashboard/os' },
    { title: 'Histórico de OS', path: '/dashboard/historico-os' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Caixa PDV (vendas diretas)', path: '/dashboard/pdv' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Designer: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Impressão: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Calandra: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Costura: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Estoque: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Produtos', path: '/dashboard/produtos' },
    { title: 'Compras', path: '/dashboard/compras' },
    { title: 'Relatórios', path: '/dashboard/relatorios' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Empacotamento: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  RH: [
    { title: 'Dashboard', path: '/dashboard/rh' },
    { title: 'Funcionários', path: '/dashboard/rh/funcionarios' },
    { title: 'Recrutamento e Seleção', path: '/dashboard/rh/recrutamento' },
    { title: 'Cargos', path: '/dashboard/rh/cargos' },
    { title: 'Setores', path: '/dashboard/rh/setores' },
    { title: 'Jornada', path: '/dashboard/rh/jornada' },
    { title: 'Escalas', path: '/dashboard/rh/escalas' },
    { title: 'Controle de Documentos', path: '/dashboard/rh/documentos' },
    { title: 'Treinamentos', path: '/dashboard/rh/treinamentos' },
    { title: 'Avaliações', path: '/dashboard/rh/avaliacoes' },
    { title: 'Perfil Comportamental (DISC)', path: '/dashboard/rh/disc' },
    { title: 'Feedbacks', path: '/dashboard/rh/feedbacks' },
    { title: 'Pesquisa de Clima', path: '/dashboard/rh/clima' },
    { title: 'Férias', path: '/dashboard/rh/ferias' },
    { title: 'Advertências', path: '/dashboard/rh/advertencias' },
    { title: 'Relatórios', path: '/dashboard/rh/relatorios' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Criar Alerta', path: '/dashboard/alerta' },
    { title: 'Assinatura Digital', path: '/dashboard/rh/assinatura' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  Recepção: [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ],
  'Administração': [
    { title: 'Dashboard', path: '/dashboard' },
    { title: 'Clientes', path: '/dashboard/clientes' },
    { title: 'Fluxo de produção (kanban)', path: '/dashboard/producao' },
    { title: 'Ordem de serviço', path: '/dashboard/os' },
    { title: 'Mensagens internas', path: '/dashboard/mensagens' },
    { title: 'Configurações', path: '/dashboard/configuracoes' },
  ]
};